
VAR SelectedDiagnosis = SELECTEDVALUE(Diagnosis_All[Diagnosis])
VAR PatientsMatchingDiagnosis =
    CALCULATETABLE(
        VALUES(Dim_Patient[Code_Patient]),
        Diagnosis_All[Diagnosis] = SelectedDiagnosis
    )
VAR DrugCount =
    IF(
        ISBLANK(SelectedDiagnosis),
        DISTINCTCOUNT(Dim_Traitement[drug]),
        CALCULATE(
            DISTINCTCOUNT(Dim_Traitement[drug]),
            Dim_Traitement[code_Traitement] IN PatientsMatchingDiagnosis
        )
    )
RETURN
COALESCE(DrugCount, 0)
